package com.study.dao.program;

public enum SubjectName {
    PHYSICS, MATH, ENGLISH, CHEMISTRY, SCIENCE_OF_LAW, INTERNATIONAL_COMMUNICATIONS,
    ELECTRICAL_ENGINEERING, PRODUCTION_EQUIPMENT, PHYSICAL_CULTURE
}
